### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sateeshperi** [bioinfologics/satsuma2#27]
Hi, I am facing the following error reported in other issues as well....attaching my error log as well.....any help in debugging this would be great. 

MAIN: STATUS: iteration, slaves_processed, new_matches, slave_to_match_relation, targets_needed, targets_collected
MAIN: STATUS: 4, 1, 1128, 1128, 0, 0, 2020/03/02 15:43:38
MAIN: starting iteration 5
WORKQUEUE: matches collected. FW: 0   REV: 0
MAIN: 0 new matches collected
MAIN: nothing changed, skipping cycle and waiting 3 seconds
ERROR: NEW Match received from slave 1 saved to position 1 looks wrong!
: 64/72 bytes received
: query_id=80
: target_id=5
: query_size=19988679
: qstart=4763964
: tstart=4695395
: len=290
: reverse=0
: prob=1
: ident=0.603774
MAIN: starting iteration 5
WORKQUEUE: matches collected. FW: 12   REV: 1855
MAIN: 1867 new matches collected
MAIN: Running the chaining step...
Matches before collapse: 237063
Matches after collapse:  236967
MAIN: running coverage tracker
MAIN: coverage tracker: +60535420 -8552
MAIN: DynProg...
Chaining (inline)...
Filling out repeat lists...
Segmentation fault (core dumped)
[satsuma2_error_log.txt](https://github.com/bioinfologics/satsuma2/files/4277892/satsuma2_error_log.txt)

**Comment by jonwright99** [comment]
Hi Sateesh,
This sounds like the same issue others have been having, probably due to your network configuration and satsuma slaves not being able to connect to the master process. To try to get around this we created a set of prebuilt binaries for Satsuma2 that you can download, copy to a directory on your HPC and run without compiling. The previous user who had this problem never got back to me about it so we were never able to test it. You can download the gzipped binaries here - https://github.com/bioinfologics/satsuma2/releases. Let me know if these work.

**Comment by sateeshperi** [comment]
@jonwright99 
It works with the new binaries. Thanks for the response

**Comment by jonwright99** [comment]
Great, glad these worked.
